apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
      annotations:
        k8s.v1.cni.cncf.io/networks: default/dmz
    spec:
      containers:
      - name: identity
        image: quay.io/keycloak/keycloak:12.0.4
        ports:
        - containerPort: 8081 #8081
        env:
        - name: KEYCLOAK_USER
          valueFrom:
            configMapKeyRef:
              name: smo-common-identity
              key: keycloak_user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: smo-common-identity
              key: keycloak_password
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: smo-common-identity
              key: java_opts
---
apiVersion: v1
kind: Service
metadata:
  name: smo-identity
spec:
  type: NodePort
  selector:
    app: identity
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8081
      targetPort: 8081
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
  labels:
    app: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
      - name: topology
        image: docker.io/hightec/smo-topology-api-v2:2.0.2-SNAPSHOT-20210315T160448Z
        ports:
        - containerPort: 3001 #3001
        env:
        - name: AUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: smo-common-topology
              key: auth_enabled
        - name: AUTH_HOST_URL
          valueFrom:
            configMapKeyRef:
              name: smo-common-topology
              key: auth_host_url
        - name: PROVIDERS
          valueFrom:
            configMapKeyRef:
              name: smo-common-topology
              key: providers
        - name: LOAD_PACKAGES
          valueFrom:
            configMapKeyRef:
              name: smo-common-topology
              key: load_packages
---
apiVersion: v1
kind: Service
metadata:
  name: smo-topology
spec:
  type: NodePort
  selector:
    app: topology
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3001
      targetPort: 3001
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
  labels:
    app: persistence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persistence
  template:
    metadata:
      labels:
        app: persistence
    spec:
      containers:
      - name: persistence
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
        env:
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              name: smo-common-persistence
              key: discovery.type
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: nexus3.onap.org:10001/onap/dmaap/zookeeper:6.0.3
        ports:
        - containerPort: 2181 #2181
        env:
        - name: ZOOKEEPER_REPLICAS
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_REPLICAS
        - name: ZOOKEEPER_TICK_TIME
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_TICK_TIME
        - name: ZOOKEEPER_SYNC_LIMIT
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_SYNC_LIMIT
        - name: ZOOKEEPER_INIT_LIMIT
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_INIT_LIMIT
        - name: ZOOKEEPER_MAX_CLIENT_CNXNS
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_MAX_CLIENT_CNXNS
        - name: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
        - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_CLIENT_PORT
        - name: KAFKA_OPTS
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: KAFKA_OPTS
        - name: ZOOKEEPER_SERVER_ID
          valueFrom:
            configMapKeyRef:
              name: smo-common-zookeeper
              key: ZOOKEEPER_SERVER_ID
        volumeMounts:
        - name: zk-server-jaas
          mountPath: /etc/zookeeper/secrets/jaas
      volumes:
      - name: zk-server-jaas
        configMap:
          name: smo-common-zookeeper
          items:
          - key: "zk_server_jaas.conf"
            path: "zk_server_jaas.conf"

---
apiVersion: v1
kind: Service
metadata:
  name: smo-zookeeper
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 2181
      targetPort: 2181
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: nexus3.onap.org:10001/onap/dmaap/kafka111:1.0.4
        ports:
        - containerPort: 9092 #9092
        env:
        - name: enableCadi
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: enableCadi
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_ZOOKEEPER_CONNECT # zookeeper:2181, replace into service
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_LISTENERS
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_INTER_BROKER_LISTENER_NAME
        - name: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE
        - name: KAFKA_OPTS
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_OPTS
        - name: KAFKA_ZOOKEEPER_SET_ACL
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_ZOOKEEPER_SET_ACL
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
          valueFrom:
            configMapKeyRef:
              name: smo-common-kafka
              key: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
        volumeMounts:
        - name: zk-client-jaas
          mountPath: /etc/kafka/secrets/jaas
      volumes:
      - name: zk-client-jaas
        configMap:
          name: smo-common-kafka
          items:
          - key: "zk_client_jaas.conf"
            path: "zk_client_jaas.conf"
---
apiVersion: v1
kind: Service
metadata:
  name: smo-kafka
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30004

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmaap
  labels:
    app: dmaap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmaap
  template:
    metadata:
      labels:
        app: dmaap
    spec:
      containers:
      - name: dmaap
        image: nexus3.onap.org:10001/onap/dmaap/dmaap-mr:1.1.18
        ports:
        - name: port1
          containerPort: 3904
        - name: port2
          containerPort: 3905
        env:
        - name: enableCadi
          valueFrom:
            configMapKeyRef:
              name: smo-common-dmaap
              key: enableCadi
        volumeMounts:
        - name: properties
          mountPath: /appl/dmaapMR1/bundleconfig/etc/appprops
        - name: logback
          mountPath: /appl/dmaapMR1/bundleconfig/etc
        - name: properties2
          mountPath: /appl/dmaapMR1/etc
      volumes:
      - name: properties2
        configMap:
          name: smo-common-dmaap
          items:
          - key: "cadi.properties"
            path: "cadi.properties"
      - name: logback
        configMap:
          name: smo-common-dmaap
          items:
          - key: "logback.xml"
            path: "logback.xml"
      - name: properties
        configMap:
          name: smo-common-dmaap
          items:
          - key: "MsgRtrApi.properties"
            path: "MsgRtrApi.properties"

---
apiVersion: v1
kind: Service
metadata:
  name: smo-dmaap
spec:
  type: NodePort
  selector:
    app: dmaap
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port3904
      port: 3904
      targetPort: 3904
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30005
    - name: port3905
      port: 3905
      targetPort: 3905
      nodePort: 30006