apiVersion: apps/v1
kind: Deployment
metadata:
  name: o-du
  labels:
    app: o-du
spec:
  replicas: 1
  selector:
    matchLabels:
      app: o-du
  template:
    metadata:
      labels:
        app: o-du
      #annotations:
      #  k8s.v1.cni.cncf.io/networks: default/dmz
    spec:
      containers:
      - name: o-du
        image: o-ran-sc/nts-ng-o-ran-du:1.3.2
        ports:
        - containerPort: 830
        env:
        - name: IPv6_ENABLED
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: IPv6_ENABLED
        - name: SSH_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SSH_CONNECTIONS
        - name: TLS_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: TLS_CONNECTIONS
        - name: NTS_NF_STANDALONE_START_FEATURES
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_NF_STANDALONE_START_FEATURES
        - name: NTS_NF_MOUNT_POINT_ADDRESSING_METHOD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_NF_MOUNT_POINT_ADDRESSING_METHOD
        - name: NTS_HOST_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_IP
        - name: NTS_HOST_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_BASE_PORT
        - name: NTS_HOST_NETCONF_SSH_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_NETCONF_SSH_BASE_PORT
        - name: NTS_HOST_NETCONF_TLS_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_NETCONF_TLS_BASE_PORT
        - name: NTS_HOST_TRANSFER_FTP_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_TRANSFER_FTP_BASE_PORT
        - name: NTS_HOST_TRANSFER_SFTP_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_HOST_TRANSFER_SFTP_BASE_PORT
        - name: NTS_BUILD_DATE
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: NTS_BUILD_DATE
        - name: SDN_CONTROLLER_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_PROTOCOL
        - name: SDN_CONTROLLER_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_IP
        - name: SDN_CONTROLLER_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_PORT
        - name: SDN_CONTROLLER_CALLHOME_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_CALLHOME_PORT
        - name: SDN_CONTROLLER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_USERNAME
        - name: SDN_CONTROLLER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: SDN_CONTROLLER_PASSWORD
        - name: VES_COMMON_HEADER_VERSION
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_COMMON_HEADER_VERSION
        - name: VES_ENDPOINT_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_PROTOCOL
        - name: VES_ENDPOINT_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_IP
        - name: VES_ENDPOINT_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_PORT
        - name: VES_ENDPOINT_AUTH_METHOD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_AUTH_METHOD
        - name: VES_ENDPOINT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_USERNAME
        - name: VES_ENDPOINT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-du
              key: VES_ENDPOINT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: o-du
spec:
  type: NodePort
  selector:
    app: o-du
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port830
      port: 830
      targetPort: 830
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30830

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: o-ru
  labels:
    app: o-ru
spec:
  replicas: 1
  selector:
    matchLabels:
      app: o-ru
  template:
    metadata:
      labels:
        app: o-ru
      #annotations:
      #  k8s.v1.cni.cncf.io/networks: default/dmz
    spec:
      containers:
      - name: o-ru
        image: o-ran-sc/nts-ng-o-ran-ru-fh:1.3.2
        ports:
        - containerPort: 830
        env:
        - name: IPv6_ENABLED
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: IPv6_ENABLED
        - name: SSH_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SSH_CONNECTIONS
        - name: TLS_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: TLS_CONNECTIONS
        - name: NTS_NF_STANDALONE_START_FEATURES
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_NF_STANDALONE_START_FEATURES
        - name: NTS_NF_MOUNT_POINT_ADDRESSING_METHOD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_NF_MOUNT_POINT_ADDRESSING_METHOD
        - name: NTS_HOST_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_IP
        - name: NTS_HOST_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_BASE_PORT
        - name: NTS_HOST_NETCONF_SSH_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_NETCONF_SSH_BASE_PORT
        - name: NTS_HOST_NETCONF_TLS_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_NETCONF_TLS_BASE_PORT
        - name: NTS_HOST_TRANSFER_FTP_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_TRANSFER_FTP_BASE_PORT
        - name: NTS_HOST_TRANSFER_SFTP_BASE_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_HOST_TRANSFER_SFTP_BASE_PORT
        - name: NTS_BUILD_DATE
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: NTS_BUILD_DATE
        - name: SDN_CONTROLLER_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_PROTOCOL
        - name: SDN_CONTROLLER_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_IP
        - name: SDN_CONTROLLER_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_PORT
        - name: SDN_CONTROLLER_CALLHOME_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_CALLHOME_PORT
        - name: SDN_CONTROLLER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_USERNAME
        - name: SDN_CONTROLLER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: SDN_CONTROLLER_PASSWORD
        - name: VES_COMMON_HEADER_VERSION
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_COMMON_HEADER_VERSION
        - name: VES_ENDPOINT_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_PROTOCOL
        - name: VES_ENDPOINT_IP
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_IP
        - name: VES_ENDPOINT_PORT
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_PORT
        - name: VES_ENDPOINT_AUTH_METHOD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_AUTH_METHOD
        - name: VES_ENDPOINT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_USERNAME
        - name: VES_ENDPOINT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: smo-simulator-ru
              key: VES_ENDPOINT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: o-ru
spec:
  type: NodePort
  selector:
    app: o-ru
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port830
      port: 830
      targetPort: 830
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30831