apiVersion: apps/v1
kind: Deployment
metadata:
  name: vescollector
  labels:
    app: vescollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vescollector
  template:
    metadata:
      labels:
        app: vescollector
      annotations:
        k8s.v1.cni.cncf.io/networks: default/dmz
    spec:
      containers:
      - name: vescollector
        image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.ves.vescollector:1.8.0 #quay.io/keycloak/keycloak:12.0.4
        ports:
        - containerPort: 8080
        - containerPort: 8443
        env:
        - name: DMAAPHOST
          valueFrom:
            configMapKeyRef:
              name: smo-oam-vescollector
              key: DMAAPHOST
        volumeMounts:
        - name: collector-properties
          mountPath: /opt/app/VESCollector/etc/collector.properties
      volumes:
      - name: collector-properties
        hostPath:
          path: /home/alan/work/oran-smo/solution/k8s/oam/ves-collector/collector.properties # Modify here
          type: FileOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: smo-ves
spec:
  type: NodePort
  selector:
    app: vescollector
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port8080
      port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
    - name: port8443
      port: 8443
      targetPort: 8443
      nodePort: 30008

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smo-onos
  labels:
    app: sdnc-onos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdnc-onos
  template:
    metadata:
      labels:
        app: sdnc-onos
      #annotations:
      #  k8s.v1.cni.cncf.io/networks: default/dmz
    spec:
      containers:
      - name: onos
        image: onosproject/onos:2.6.0
        ports:
        - containerPort: 8181
        - containerPort: 8101
        - containerPort: 5005
        - containerPort: 830

---
apiVersion: v1
kind: Service
metadata:
  name: smo-onos
spec:
  type: NodePort
  selector:
    app: sdnc-onos
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port8181
      port: 8181
      targetPort: 8181
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009
    - name: port8101
      port: 8101
      targetPort: 8101
      nodePort: 30010
    - name: port5005
      port: 5005
      targetPort: 5005
      nodePort: 30011
    - name: port830
      port: 830
      targetPort: 830
      nodePort: 30012